# Generated by Django 3.2.9 on 2022-12-04 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(null=True, upload_to='images')),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='dp',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
