# Generated by Django 3.2.9 on 2022-12-04 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('chat', '0002_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='members',
            field=models.ManyToManyField(to='users.Profile'),
        ),
    ]
